language: java

jdk:
  - openjdk8
#  - openjdk11

services:
  -docker

#before_script:
#  - pip install docker-compose

#script: ant build

#before_install:
#  - cd java

#before_script:
#  - mv -r DataAnalysis/src .

#script:
#  - ant test